image: node:latest

cache:
  paths:
    - node_modules/

pages:
  stage: deploy
  script:
    - yarn install
    - ./node_modules/.bin/quasar build
    - cp -r dist/spa/. public
  artifacts:
    paths:
      - public
  only:
    - main
